### ISSUE TITLE
 Fixed menu bar

### ISSUE THREAD

**Issue by jorgenavarrobeltran** [pkp/healthSciences#105]
hello, please, who could help me set the top menu bar?

the idea is that when you download the page, the menu bar remains on top

**Comment by Vitaliy-1** [comment]
Hi @jorgenavarrobeltran 

Hmm, what exactly you want to do with a menu bar and which one (user or primary).
Nevertheless, to make some element sticky, in CSS you can apply position sticky: https://www.w3schools.com/howto/howto_css_sticky_element.asp
