### ISSUE TITLE
Wrong PDF view header shown in child themes

### ISSUE THREAD

**Issue by mittinatten** [pkp/healthSciences#107]
Hi,
Not sure if this is a problem with OJS in general or this plugin: We use healthSciences as a base theme and then add our customized templates and css in a child theme, which generally works fine. The overridden PDF view header from healthSciences (`templates/plugins/generic/pdfJsViewer/templates/display.tpl`) is however not shown in our child theme, instead we get the original one from OJS. If we copy the healthSciences one to the child theme it is shown. I assume there is some confusion in OJS when deciding override priority, is there anything we can do avoid keeping a separate copy of the template, or should this be reported as a bug to ojs/pkp-lib?

Simon

**Comment by Vitaliy-1** [comment]
Hi @mittinatten 
Yep, I think it is better to open this as a general issue in OJS. I suspect that the method that had implemented the possibility of overriding plugins' templates doesn't take into account the path from a parent theme when a child theme is used.

**Comment by mittinatten** [comment]
Ok, will do!

**Comment by Vitaliy-1** [comment]
Should be fixed.
