### ISSUE TITLE
Lists in the footer

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/healthSciences#11]
Think it is better to set `list-style-type` to none for lists in the footer. But it is a matter of tastes actually.
![lists-in-footer](https://user-images.githubusercontent.com/20665587/36643023-1696c738-1a4f-11e8-9861-035a0d16dfa2.jpg)

**Comment by NateWr** [comment]
Thanks! I decided to just tackle the known block feed lists in case people want to use lists in custom block elements.
