### ISSUE TITLE
Support for right to left script

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/healthSciences#122]
Reference on how it's handled in OJS: https://github.com/pkp/pkp-lib/issues/1906
Related to: https://forum.pkp.sfu.ca/t/converting-health-science-theme-to-rtl/49815

@NateWr Do you see other option than adding a form an entry to a database through Theme API? Maybe check the language and upload styles automatically? As it is needed to all themes I'm inclined to adding a method inside `ThemePlugin` class to check language. 

**Edit**: It seems that OJS has already such method, right?

**Comment by NateWr** [comment]
The default header for themes adds a `dir=...` attribute to the body tag:

https://github.com/pkp/pkp-lib/blob/master/templates/frontend/components/header.tpl#L25

Use this to write styles for RTL languages:

```
body[dir="rtl] {
  ...
}
```

That's what we use for the OJS backend: https://github.com/pkp/pkp-lib/blob/master/templates/frontend/components/header.tpl#L25

**Comment by Vitaliy-1** [comment]
This should be enough.
