### ISSUE TITLE
Is it possible to add an announcement to the front page?

### ISSUE THREAD

**Issue by rtsaboya** [pkp/healthSciences#125]
Hello!
I was wondering if it is possible to add an announcement to the front page. I already checked the "Display X of the most recent announcements on the journal homepage" option, but to no avail.

Checking the file [indexJournal.tpl](https://github.com/pkp/healthSciences/blob/master/templates/frontend/pages/indexJournal.tpl), I noticed that it mentions "$numAnnouncementsHomepage" in the comments, abut apparently it doesn't use it in the body.

Am I missing something?

Best, 
Renato.

**Comment by rtsaboya** [comment]
Sorry, once again I posted a question before digging deeper into the issue. I managed to put an announcement in the home page by including the following before `{* make the entire block conditional if there aren't any additional issue data *}`:

`
		{* Announcements *}
		{if $numAnnouncementsHomepage && $announcements|@count}
			<div class="homepage-issue-description-wrapper">
				<h2>
					{translate key="announcement.announcements"}
				</h2>
				{foreach name=announcements from=$announcements item=announcement}
					{if $smarty.foreach.announcements.iteration > $numAnnouncementsHomepage}
						{php}break;{/php}
					{/if}
					{if $smarty.foreach.announcements.iteration == 1}
						{include file="frontend/objects/announcement_summary.tpl" heading="h3"}
						<div class="more">
					{else}
						<article class="obj_announcement_summary">
							<h4>
								<a href="{url router=$smarty.const.ROUTE_PAGE page="announcement" op="view" path=$announcement->getId()}">
									{$announcement->getLocalizedTitle()|escape}
								</a>
							</h4>
							<div class="date">
								{$announcement->getDatePosted()}
							</div>
						</article>
					{/if}
				{/foreach}
				</div>
			</div>
		{/if}
`

Thanks!

**Comment by Vitaliy-1** [comment]
Hi @rtsaboya 

We are planning to add announcements on the journal index page in one of the future releases. Maybe you have some design propositions for this?

**Comment by rtsaboya** [comment]
I just put another "homepage-issue-description-wrapper" div and thought that it blended quite nicely. See the attached image. It worked well for short and long announcements. 

For two or more announcements some tweaking is necessary, but nothing very hard, I think. 

![screenshot---18_12_2018- -18_28_43](https://user-images.githubusercontent.com/1327871/50181622-0b843400-02f4-11e9-8584-b88ba55d5a44.png)
![screenshot---18_12_2018- -18_24_14](https://user-images.githubusercontent.com/1327871/50181623-0b843400-02f4-11e9-9b99-f73216719d3b.png)
