### ISSUE TITLE
Properly escape resultsFor locale key

### ISSUE THREAD

**Issue by asmecher** [pkp/healthSciences#128]
The resultsFor locale key includes variables without properly escaping them.

**Comment by asmecher** [comment]
PR: https://github.com/pkp/healthSciences/pull/129

@Vitaliy-1 and @NateWr, please watch out for these! I'd suggest putting together a new build to resolve it.

**Comment by Vitaliy-1** [comment]
Sure! Thanks, didn't notice this.

**Comment by NateWr** [comment]
@asmecher looks like Vitaliy did the release: https://github.com/pkp/healthSciences/releases/tag/1.0.3. Are you able to update the `plugins.xml` file? I seem to have an issue with it in my current dev setup so can't do it easily. But if not I can figure it out.

**Comment by asmecher** [comment]
Done, thanks!
