### ISSUE TITLE
Change the default fonts

### ISSUE THREAD

**Issue by issetgg** [pkp/healthSciences#133]
Hi, Is it possible to change the default fonts? I want another font instead of 'Droid Serif' and edited two files: HealthSciencesThemePlugin.inc.php and variables.less 

But the result is a mess and i don't know if it is necessary to modify another file.

Thanks for the help.

**Comment by sssoz** [comment]
@issetgg Would you be able to send me a screenshot, or tell me where the fonts that haven’t been changed appear?

**Comment by issetgg** [comment]
Hi @sssoz, thanks for answering. I solved my problem, I did tests with different fonts and the one that was left was Roboto Condensed. At this moment I can not generate a screenshot with the error because the development is already advanced and we are about to publish the magazine but I attached an image of the advance

![anales-iie-unam](https://user-images.githubusercontent.com/1843700/55580069-f5e61f00-56d6-11e9-913e-ab5a0a2e25b3.png)

Thank you very much for sharing your work.
