### ISSUE TITLE
Not work on OJS 3.1.2

### ISSUE THREAD

**Issue by navotera** [pkp/healthSciences#136]
OJS 3.1.2 does not load any of template file from this theme.

For example when the page load on the home index, it should load the template file from this theme
->bootstrap 3
-> templates
->frontend
->all custom template file such as indexSite.tpl, header.tpl or other partials template files within this theme.

But it does not load any of those custom smarty files (*.tpl), the page is accessed only load the default layout from the lib->pkp->templates.

And I could say that this is work on the previous version (OJS 3.1.1).

I curious and install another theme specifically healthscience theme and you know what it does not work too.

Is there some configuration that need to activate to use the custom template file for custom theme for the ojs 3.1.2 since it works flawlessly on the previous OJS version ?
Thank

**Comment by navotera** [comment]
here the preview of the index page when using this theme : 

![image](https://user-images.githubusercontent.com/1424851/54326061-17a43700-4640-11e9-965c-1757eb0084ed.png)

**Comment by Vitaliy-1** [comment]
Hi @navotera

Thanks for spotting!
This is an OJS related issue that happens on Windows OS because of uncounted directory separator. You were right, the issue comes from `_overridePluginTemplates` method; let's follow the topic here: https://github.com/pkp/pkp-lib/issues/4600
