### ISSUE TITLE
'/' character is URL encoded in navigation menu items

### ISSUE THREAD

**Issue by duknic** [pkp/healthSciences#139]
New to OJS, so if this is not specific to this theme then please ignore.

Given a top level navigation page `example.com/faqs`.
Create a custom page and give it path value of `/faqs/number-one`.
In 'Navigation Menus' nest the custom page underneath faq page.
Browsing directly to `example.com/faqs/number-one` displays the page.
Cannot use the navigation to browse there as the path in the link has been url encoded, e.g. `example.com/faqs%2Fnumber-one`.

**Comment by Vitaliy-1** [comment]
Hi @duknic,

Does this work normally with other themes, or it's just related to the Health Sciences?
