### ISSUE TITLE
Can't select the theme

### ISSUE THREAD

**Issue by mayolag** [pkp/healthSciences#144]
Hello
I’m using OJS 3.1.2. I already installed the theme through ftp (I was unable to install it otherwise). I successfully activated it, however I’m unable to select it in the Appearance drop down. 
Please help!
<img width="1051" alt="theme" src="https://user-images.githubusercontent.com/28739381/55674739-f79a1900-5875-11e9-88c7-1af3c34eecb4.png">

**Comment by Vitaliy-1** [comment]
Hi @mayolag,

Are you using Windows as a server?
Have you activated the theme plugin for the specific journal?
Do you see any relevant errors in the php error.log?
What problems have you encountered when tried to download it through a plugin gallery?

**Comment by mayolag** [comment]
I am hosting the journal in a linux server. I activated the plugin for an specific jounal (I'm only hosting one). Didn't find any errors in the php error.log. What I did have was trouble downloading through the plugin gallery. I can't install any plugin from there, nothing happens after I click "ok". So I manually downloaded and installed the theme via ftp.

<img width="777" alt="Screen Shot 2019-04-08 at 11 47 40" src="https://user-images.githubusercontent.com/28739381/55741956-24743a80-59f4-11e9-9271-fbcf59770bc8.png">

**Comment by Vitaliy-1** [comment]
Have you used the [latest release](https://github.com/pkp/healthSciences/releases/tag/1.0.4)? Or you have directly downloaded the code from the master branch?

**Comment by Vitaliy-1** [comment]
And another important question.
Can you browse to the themes directory and confirm that it's named `healthSciences` and has sufficient permission for the apache server to read?

**Comment by mayolag** [comment]
I downloaded the latest release. I don't know how to set permissions...

**Comment by Vitaliy-1** [comment]
It depends on the server configurations. I'm working with Ubuntu: https://help.ubuntu.com/community/FilePermissions
The apache user is usually `www-data`, so, in my case I set `sudo chmod -R 740 themeDirectory`. Where 7 means give a full access to the user, 4 - read access for the group (www-data) and 0 - forbid any operations for others. -R here stands for recursively  - for all files and folders inside.
The ownership can be set as `sudo chown -R user:group themeDirectory`. Once again, in my case group is `www-data`.

**Comment by mayolag** [comment]
But I'm using cpanel

**Comment by Vitaliy-1** [comment]
I'm not familiar with the CPanel. Let's assume that permissions are set right. Can you look at the name of the directory for Health Sciences theme inside 'plugins/themes'?

**Comment by mayolag** [comment]
Ok, that was the problem, it was named healthSciences Master.
Thank you very much

**Comment by Vitaliy-1** [comment]
Great to hear that the issue is resolved!
