### ISSUE TITLE
Problems with display of some information in Cyrillic

### ISSUE THREAD

**Issue by novikoffav** [pkp/healthSciences#148]
Hi!
I have instaled OJS 3.1.1.4 with two-language (English/Ukrainian) interface with HealthScience 1.0.2 style. In English version all information is displayed properly, but when I switch to Ukrainian version I am getting issues - some information (like a date of publication) is not displayed and there is some code (e.g. ##plugins.themes.healthSciences.currentIssuePublished##) instead. 
Is it possible to fix it somehow. At least I would like to display this information in English in both versions (English and Ukrainian) of vebsite, if it is not possible to display it in Ukrainian.
Please also see screenshots.
Thanks for help!
![Screenshot_1](https://user-images.githubusercontent.com/22555461/57299211-a8e1d800-70dc-11e9-8345-42b9d467a871.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/22555461/57299212-a8e1d800-70dc-11e9-8804-f81adfd2a511.jpg)
![Screenshot_3](https://user-images.githubusercontent.com/22555461/57299213-a8e1d800-70dc-11e9-9d4a-d1911a9606b7.jpg)
![Screenshot_4](https://user-images.githubusercontent.com/22555461/57299215-a97a6e80-70dc-11e9-80b3-367debc86e1d.jpg)

**Comment by Vitaliy-1** [comment]
Hi @novikoffav 

This tag needs to be translated into Ukrainian. English locale files have the most full translation: https://github.com/pkp/healthSciences/blob/master/locale/en_US/locale.xml. The correspondent locale tag should be added into Ukrainian locale: https://github.com/pkp/healthSciences/blob/master/locale/uk_UA/locale.xml
