### ISSUE TITLE
Redundant horizontal line on index journal page 

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/healthSciences#150]
It was added with a [commit regarding announcements](https://github.com/pkp/healthSciences/commit/c73c823e19741f940175b1539f2f8a3e435c7e59), comes from `.page-content` class: https://github.com/pkp/healthSciences/blob/master/templates/frontend/pages/indexJournal.tpl#L27
related style: https://github.com/pkp/healthSciences/blob/master/styles/pages/page-common.less#L23

The correspondent topic on forum: https://forum.pkp.sfu.ca/t/health-science-theme-horizontal-line/53879

@sssoz, is the idea to display it conditionally when announcements are present?

**Comment by sssoz** [comment]
This was a mistake - the border is meant to be displayed at the top of `.page-content` on pages like this: https://medicinaclinica.org/index.php/rmc/about (under the page’s title). 

I will fix this - the `.page-content` class is a more generic one than `.container-homepage-issue` and thus should be before `.container-homepage-issue`.
