### ISSUE TITLE
Add the top search bar

### ISSUE THREAD

**Issue by jorgenavarrobeltran** [pkp/healthSciences#18]
The theme is a masterpiece, here I leave it as it is: http://revistas.unilibre.edu.co/ingeniare
The only thing missing is that please add the top search bar

**Comment by Vitaliy-1** [comment]
Search page can be accessed through a menu button. Do you think that this is inconvenient somehow? If adding search bar, where you propose it to be situated?

**Comment by kwahyu** [comment]
another super contribution by @Vitaliy-1 and team. I think the way oldGregg presents Search is good idea.

**Comment by kwahyu** [comment]
Dear @Vitaliy-1 
I have not got the search menu in nav bar. http://ulumuna.or.id/index.php/ujis/index

**Comment by Vitaliy-1** [comment]
@kwahyu 
You need to add a search page button in the primary menu
