### ISSUE TITLE
Issue with Arabic layout in Internet Explorer

### ISSUE THREAD

**Issue by amandastevens** [pkp/healthSciences#182]
PKP PS client @hkamareddineiiit reported that when using the Health Sciences theme on the journal's OJS 3.1.1 site, everything displays fine in Chrome and Firefox, but in Internet Explorer the direction of the template and text are from left to right which is wrong for Arabic. The client added a direction tag in html for some of them, but can't control others and the template itself. 

Here are the affected pages:

https://citj.org/index.php/citj/issue/view/291
https://citj.org/index.php/citj/issue/view/291
https://citj.org/index.php/citj/about/AimsAndScope
https://citj.org/index.php/citj/about/openaccess
https://citj.org/index.php/citj/about/submissions

Tagging the client in case there are follow-up questions.

**Comment by Vitaliy-1** [comment]
Internet Explorer doesn't support `initial` global property value: https://developer.mozilla.org/en-US/docs/Web/CSS/initial

**Comment by Vitaliy-1** [comment]
I don't have IE to test but it should work. Just let me know if doesn't. The commits are to master, stable-3_1_2, and stable-3_1_1 branches of the theme plugin. If all works as expected the issue can be closed.

**Comment by hkamareddineiiit** [comment]
Hello and thank you for your support. Unfortunately it still doesn't look aligned from right to left. I attached 2 screen shots as an example. The text and buttons should all be aligned from right to left.
Let me know if you need anything else. best, huda

![IE RTL 1](https://user-images.githubusercontent.com/63079455/79120570-330cd480-7d61-11ea-93bd-fa6ae5e3392b.png)
![IE RTL 2](https://user-images.githubusercontent.com/63079455/79120574-36a05b80-7d61-11ea-9237-65b4d706d5f1.png)

**Comment by hkamareddineiiit** [comment]
Note: you could check the right direction by looking at www.citj.org in Chrome. Thanks!

**Comment by Vitaliy-1** [comment]
Hi @hkamareddineiiit,

I don't see that that change is applied. I'm not sure how you add it.
If uploading custom CSS, it should look like:
```
body[dir="rtl"] {
  text-align: right;
}
```
If updating with Git, make sure to checkout the branch of the plugin that corresponds to OJS version. 
It also may require clearing template and browser cache.

**Comment by hkamareddineiiit** [comment]
I don't use CSS. Perhaps @amandastevens can help?

**Comment by amandastevens** [comment]
@hkamareddineiiit, you will need to create and upload a custom stylesheet under Website Settings > Appearance > Journal Stylesheet. A CSS can be used to make minor adjustments to the theme. There are instructions on how to do it in the [Designing Your Journal Guide](https://docs.pkp.sfu.ca/designing-your-journal/en/creating-stylesheet).

**Comment by hkamareddineiiit** [comment]
Done! Thank you both! @amandastevens @Vitaliy-1
