### ISSUE TITLE
Footer content not showing

### ISSUE THREAD

**Issue by rtsaboya** [pkp/healthSciences#183]
Hello!
I cannot make my footer content appear on the homepage. I fill in some text in Website settings > Appearance > Page footer but nothing changes. The widgets of the sidebar do appear, though.

Am I missing something?

Best,
Renato.

**Comment by ViRuSTriNiTy** [comment]
Try to clear the template cache...

**Comment by rtsaboya** [comment]
Thank you! I had not done that, but now I did and it did not solve the problem. 

Any other suggestion?

**Comment by ViRuSTriNiTy** [comment]
Perhaps you are thinking in the wrong context? The page footer setting is present in Website context (specific journal) and overall Site context. Tested both contexts and it works.

**Comment by rtsaboya** [comment]
I made the changes in Website settings > Appearance > Page footer. Is there any other place for that? My site has only one journal, so I assume everything is associated with it (maybe that's where my mistake is).

Thanks again!

**Comment by ViRuSTriNiTy** [comment]
Hmm maybe its a language issue as the footer content is localized data? Do you run a multi language journal?

**Comment by rtsaboya** [comment]
It's not that either, as I have something filled for both languages, and none appear on the front end regardless of the language I choose.

**Comment by Vitaliy-1** [comment]
Can't reproduce this either. @rtsaboya, is the issue still relevant?

**Comment by rtsaboya** [comment]
@Vitaliy-1, unfortunately yes.
I updated the theme (1.0.6.1) but nothing  happens. Please see attached images.
Thanks for any suggestion!

![opera_2020_06_19_09_27_43](https://user-images.githubusercontent.com/1327871/85132887-1634c780-b210-11ea-9822-ec99fac1497d.png)
![opera_2020_06_19_09_27_33](https://user-images.githubusercontent.com/1327871/85132892-17fe8b00-b210-11ea-9651-2789560c9deb.png)

**Comment by Vitaliy-1** [comment]
Do you have access to the database to check if the page footer is being saved? 
```
SELECT * FROM journal_settings WHERE setting_name = 'pageFooter'
```
Should show this setting for all the journals

**Comment by rtsaboya** [comment]
Dears @Vitaliy-1 and @ViRuSTriNiTy :
Thank you so much for your assistance. I ran the SQL query and determined that the option was correctly set in the database. Then I had the idea of inspecting the page and found out that the text was indeed there, but in the same color as the background.

I'm sorry to have bothered you with such a newbie's problem. All is right now.

Thanks so much for this great theme!
