### ISSUE TITLE
Sidebar and columns

### ISSUE THREAD

**Issue by gkmnarslan** [pkp/healthSciences#184]
Hi everyone,

I am working to modify the Health Science Theme with OJS 3.2.03.
I need to help about the following;
First, how can I add a sidebar on the homepage?
Second, I want to present articles in two columns, like OldGregg. How can I do it?

Thank you in advance

**Comment by Vitaliy-1** [comment]
I believe that this question was answered on the forum: https://forum.pkp.sfu.ca/t/health-science-theme/60600
Thus, closing.
