### ISSUE TITLE
Typo in template searchAuthorDetails.tpl

### ISSUE THREAD

**Issue by asmecher** [pkp/healthSciences#185]
See https://github.com/pkp/healthSciences/blob/6020043db89666fad11492acb8098d711bb6d7f5/templates/frontend/pages/searchAuthorDetails.tpl#L44:
```
{if (!$issueUnavailable || $publication->getData('accessStatus') == $smarty.const.ARTICLE_ACCESS_OPEN}}
```
The `}}` at the end should be `)}`. The mistake causes:

```
PHP Fatal error:  Uncaught  --> Smarty Compiler: Syntax error in template "app:app:frontendpagessearchAuthor"  on line 44 "{if (!$issueUnavailable || $publication->getData('accessStatus') == $smarty.const.ARTICLE_ACCESS_OPEN}}"  - Unexpected "}" <-- \n  thrown in /.../lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatecompilerbase.php on line 44
```

**Comment by asmecher** [comment]
@NateWr, this appears to only affect the `master` branch of `healthSciences`. I'm not sure how releases on this repo are planned but this might justify one?

**Comment by NateWr** [comment]
It looks like there was a release 5 days ago that includes this: https://github.com/pkp/healthSciences/releases/tag/1.0.7.0. I guess we just need to make sure that the plugins.xml has the latest release.
