### ISSUE TITLE
Author-plus does not hide when there are two authors

### ISSUE THREAD

**Issue by epistemehealth** [pkp/healthSciences#187]
**Describe the bug**
When there are two authors, the plus next to the author's name does not hide and turn into a minus when clicking on them to reveal more information about their affiliation.
Example: 
Joel S. Mtebe+, Roope Raisamo+

**To Reproduce**
https://demo.publicknowledgeproject.org/ojs3/demo/index.php/health-sciences/article/view/716

**Expected behavior**
When clicking on the author's names, the + should turn to a - sign.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/52137396/83993430-69aa3a00-a921-11ea-9151-4ba8dcefcb15.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version: 77

**Additional context**
Can be fixed by moving one of the closing curly braces+brackets from line 47 to line 34 in [main.js](https://github.com/pkp/healthSciences/blob/master/js/main.js).

**Comment by Vitaliy-1** [comment]
Thanks! Your solution solves the issue.
