### ISSUE TITLE
copyrightHolder variable needs to be localized

### ISSUE THREAD

**Issue by jnugent** [pkp/healthSciences#192]
The $copyrightHolder variable is passed from the page handler to the theme as an array of localized data, so as it stands now the theme prints "Array" instead of the localized string.  The theme needs the adjustment in the default article_details.tpl template instead.

**Comment by Vitaliy-1** [comment]
Thanks! There were changes introduced in licensing information that I haven't noticed. Several variables, including `copyrightHolder` are deprecated and `licenseTerms` was separated from `copyrightNotice`. Missed new form with licensing info that appeared in distribution settings. During upgrade license terms should be populated with value from copyright notice according to the upgrade script, so it shouldn't cause any problems.

**Comment by Vitaliy-1** [comment]
Now should be solved.
