### ISSUE TITLE
Plugin can't be installed through plugin upload tool

### ISSUE THREAD

**Issue by asmecher** [pkp/healthSciences#2]
I think the issue relates to the fact that the plugin installer currently looks for a `lib` subdirectory in the plugin area, and if one exists, it tries to put files there into `lib/pkp/plugins/...`. (This is an old mechanism that we're replacing gradually with plugins in their own repos.) I'd suggest using `libs` rather than `lib` for the moment to avoid the collision.

**Comment by asmecher** [comment]
@NateWr, is this theme now installable with OJS 3.1.0-1 using the web-based installer?

**Comment by NateWr** [comment]
It should be. I haven't tested it but the directory was renamed. I'm going to do a beta release tomorrow and will test the release package.

**Comment by asmecher** [comment]
Perfect, thanks!
