### ISSUE TITLE
DOI does not appear in article summary on some search results pages

### ISSUE THREAD

**Issue by NateWr** [pkp/healthSciences#208]
**Describe the bug**
The DOI appears in the article summary on the journal index and the issue table of contents. However, in some cases it doesn't appear in the search results. If the search results page is shown at `/search` then the DOI appears. If it is at `/search/search` then the DOI does not appear.

It should be possible to fix this by checking `$requestedPage === 'search' in the article summary template at https://github.com/pkp/healthSciences/blob/main/templates/frontend/objects/article_summary.tpl#L56-L78.

**To Reproduce**
1. Publish an article with a DOI
2. Search for it.
3. Change search URL as described above.

**Expected behavior**
The DOI should always appear in search results, regardless of which URL is used. 

**Screenshots**
See examples in [forum](https://forum.pkp.sfu.ca/t/search-url-edit/66606).

**Comment by ruienf** [comment]
Hi @NateWr , thank you for opening this issue.

I'd like to add another related situation: in the catalog/category pages (it uses article_summary.tpl as well), there's also no DOI:

https://rper.aper.pt/index.php/rper/catalog/category/revisaoliteratura

Thank you very much for your help!

Rui Pedro Silva

**Comment by ruienf** [comment]
Hi @NateWr !

I think I made it work and it seems ok... however, I don't know if my workaround will mess up something, so I'd appreciate some opinions from someone who´s not a beginner like me... :)

Basically, I search for 'search' 'search' appearances in the code and, digging a little bit, the op="search" info. And I made this chages:

File plugins/themes/healthSciences/templates/frontend/pages/search.tpl:
- replaced _**op="search"**_ by **_op=""_** (about line 61, I'm using a modified search.tpl file)

File plugins/generic/recommendBySimilarity/templates/articleFooter.tpl (I'm using this plugin):
- replaced **_op="search"_** by _**op=""**_  (line 38)

File pages/search/SearchHandler.inc.php:
- replaced  _**$request->redirect(null, 'search', 'search', null, $searchParams);**_ by  _**$request->redirect(null, 'search', null, null, $searchParams);**_ (line 179)

File lib/pkp/classes/services/PKPNavigationMenuService.inc.php:
- replace **_'search',_** by **_null,_** (line 342)

For me, it's working!

PS: This is my first comment with code in it, please tell me if I mentioned it the right way...

Thank you!

Rui Pedro Silva

**Comment by ruienf** [comment]
Hi!

Ok great!!!

I'll try to fix it in the catalog/category page as well.

Thank you!

Rui Pedro Silva





Nate Wright ***@***.***> escreveu no dia quarta, 24/03/2021
à(s) 09:57:

**Comment by NateWr** [comment]
@ruienf the change at https://github.com/pkp/healthSciences/commit/3f08776b840e456951249dbc2c3e54dc4de77d0e should make it work for the catalog pages too.

**Comment by ruienf** [comment]
Yes, perfect!!!

**Comment by Vitaliy-1** [comment]
@NateWr, looks good, just one small comment.

I didn't mean to show DOIs there when implemented this feature but don't have any objections.

**Comment by ruienf** [comment]
Hi!

Maybe it could become a optional feature; it would be useful, IMO, to
select what fields appear on search and catalog results.

For example, I used a previous post (
https://forum.pkp.sfu.ca/t/solved-customize-the-search-template-to-display-the-year-volume-and-number-instead-of-page-numbers/38812/3)
to display the issue series in the search results (as in
https://rper.aper.pt/index.php/rper/search/index?query=reabilita%C3%A7%C3%A3o).
A feature allowing several fields to be selected for the search results and
catalog display would be nice! :)

Can I help in anything for that to happen?

Thank you!

Rui Pedro Silva

**Comment by NateWr** [comment]
> Maybe it could become a optional feature

As a small team maintaining a large codebase, we have to be careful about what features and options we support, or else we get overwhelmed by the burden of maintaining all that extra code over time.

I'd recommend considering a child theme for this purpose. You can use the [theme options API](https://docs.pkp.sfu.ca/pkp-theming-guide/en/theme-options-api) to build a child theme with the option and release it publicly on the OJS plugin gallery.

**Comment by ruienf** [comment]
Hi!

We're already using a healthSciences child theme, that's where we're "trial
and error" it... :)

 I'll give it a try and I'll keep you posted.

Have a great week!

*Rui Pedro Silva*
