### ISSUE TITLE
browseBySection template is out of date with plugin and no sections are displayed

### ISSUE THREAD

**Issue by jnugent** [pkp/healthSciences#218]
**Describe the bug**
The template included in the theme for the browseBySection plugin uses older iteration code and does not factor in the changes made to the plugin, which now uses articleGroups and an array-of-arrays approach to pass in the articles that should be displayed.  As a result no sections are listed when this theme is enabled, even if articles are assigned to the section.

Now we have this:

https://github.com/pkp/browseBySection/blob/main/templates/frontend/pages/section.tpl#L33

but the theme is still doing this:

https://github.com/pkp/healthSciences/blob/main/templates/plugins/generic/browseBySection/templates/frontend/pages/section.tpl#L36

Seen in OJS 3.3.0.10

**Comment by Vitaliy-1** [comment]
Thanks, fixed on `main` and `stable-3_3_0`
