### ISSUE TITLE
if i try to enable or disable the plugin from a journal settings page the complete journal is showing 500 error

### ISSUE THREAD

**Issue by paulyss** [pkp/healthSciences#236]
When i try to install or remove the plugin healthscience from the main journal admin page or the journal settings page the complete journal is throwing an http 500 error. so now i am unable to open some of my journal pages, setting pages and the main admin page. 

here is the php error log 

[22-Aug-2023 18:27:50 UTC] PHP Fatal error:  Uncaught Exception: Invalid product name "ojs-health-sciences" in /home/customer/www/****/public_html/journals/lib/pkp/classes/plugins/PluginRegistry.php:186
Stack trace:
#0 /home/customer/www/****/public_html/journals/lib/pkp/classes/plugins/PluginRegistry.php(219): PKP\plugins\PluginRegistry::_instantiatePlugin('themes', 'ojs-health-scie...', 'HealthSciencesT...')
#1 /home/customer/www/****/public_html/journals/lib/pkp/classes/plugins/PluginRegistry.php(112): PKP\plugins\PluginRegistry::_loadFromDatabase('themes', NULL)
#2 /home/customer/www/****/public_html/journals/lib/pkp/classes/template/PKPTemplateManager.php(1392): PKP\plugins\PluginRegistry::loadCategory('themes', true)
#3 /home/customer/www/****/public_html/journals/lib/pkp/classes/plugins/Plugin.php(403): PKP\template\PKPTemplateManager::getManager(Object(APP\core\Request))
#4 /home/customer/www/****/public_html/journals/lib/pkp/classes/plugins/Plugin.php(137): PKP\plugins\Plugin->_registerTemplateResource()
#5 /home/customer/www/****/public_html/journals/lib/pkp/classes/plugins/LazyLoadPlugin.php(34): PKP\plugins\Plugin->register('generic', 'plugins/generic...', NULL)
#6 /home/customer/www/****/public_html/journals/plugins/generic/pdfJsViewer/PdfJsViewerPlugin.php(31): PKP\plugins\LazyLoadPlugin->register('generic', 'plugins/generic...', NULL)
#7 /home/customer/www/****/public_html/journals/lib/pkp/classes/plugins/PluginRegistry.php(76): APP\plugins\generic\pdfJsViewer\PdfJsViewerPlugin->register('generic', 'plugins/generic...', NULL)
#8 /home/customer/www/****/public_html/journals/lib/pkp/classes/plugins/PluginRegistry.php(121): PKP\plugins\PluginRegistry::register('generic', Object(APP\plugins\generic\pdfJsViewer\PdfJsViewerPlugin), 'plugins/generic...', NULL)
#9 [internal function]: PKP\plugins\PluginRegistry::PKP\plugins\{closure}(Object(APP\plugins\generic\pdfJsViewer\PdfJsViewerPlugin), 'plugins/generic...')
#10 /home/customer/www/****/public_html/journals/lib/pkp/classes/plugins/PluginRegistry.php(121): array_walk_recursive(Array, Object(Closure))
#11 /home/customer/www/****/public_html/journals/lib/pkp/classes/core/Dispatcher.php(155): PKP\plugins\PluginRegistry::loadCategory('generic', true)
#12 /home/customer/www/****/public_html/journals/lib/pkp/classes/core/PKPApplication.php(373): PKP\core\Dispatcher->dispatch(Object(APP\core\Request))
#13 /home/customer/www/****/public_html/journals/index.php(21): PKP\core\PKPApplication->execute()
#14 {main}
  thrown in /home/customer/www/****/public_html/journals/lib/pkp/classes/plugins/PluginRegistry.php on line 186
[22-Aug-2023 18:27:52 UTC] Exception: Plugin markup expected to inherit from MarkupPlugin, actual type NULL in /home/customer/www/****/public_html/journals/lib/pkp/classes/plugins/PluginRegistry.php:203
Stack trace:
#0 /home/customer/www/****/public_html/journals/lib/pkp/classes/plugins/PluginRegistry.php(219): PKP\plugins\PluginRegistry::_instantiatePlugin('generic', 'markup', 'MarkupPlugin')
#1 /home/customer/www/****/public_html/journals/lib/pkp/classes/plugins/PluginRegistry.php(112): PKP\plugins\PluginRegistry::_loadFromDatabase('generic', NULL)
#2 /home/customer/www/****/public_html/journals/lib/pkp/classes/core/Dispatcher.php(155): PKP\plugins\PluginRegistry::loadCategory('generic', true)
#3 /home/customer/www/****/public_html/journals/lib/pkp/classes/core/PKPApplication.php(373): PKP\core\Dispatcher->dispatch(Object(APP\core\Request))
#4 /home/customer/www/****/public_html/journals/index.php(21): PKP\core\PKPApplication->execute()
#5 {main}
[22-Aug-2023 18:27:52 UTC] Exception: Plugin shibboleth expected to inherit from ShibbolethAuthPlugin, actual type NULL in /home/customer/www/****/public_html/journals/lib/pkp/classes/plugins/PluginRegistry.php:203
Stack trace:
#0 /home/customer/www/****/public_html/journals/lib/pkp/classes/plugins/PluginRegistry.php(219): PKP\plugins\PluginRegistry::_instantiatePlugin('generic', 'shibboleth', 'ShibbolethAuthP...')
#1 /home/customer/www/****/public_html/journals/lib/pkp/classes/plugins/PluginRegistry.php(112): PKP\plugins\PluginRegistry::_loadFromDatabase('generic', NULL)
#2 /home/customer/www/****/public_html/journals/lib/pkp/classes/core/Dispatcher.php(155): PKP\plugins\PluginRegistry::loadCategory('generic', true)
#3 /home/customer/www/****/public_html/journals/lib/pkp/classes/core/PKPApplication.php(373): PKP\core\Dispatcher->dispatch(Object(APP\core\Request))
#4 /home/customer/www/****/public_html/journals/index.php(21): PKP\core\PKPApplication->execute()
#5 {main}
[22-Aug-2023 18:27:52 UTC] Exception: Plugin paperbuzz expected to inherit from PaperbuzzPlugin, actual type NULL in /home/customer/www/****/public_html/journals/lib/pkp/classes/plugins/PluginRegistry.php:203
Stack trace:
#0 /home/customer/www/****/public_html/journals/lib/pkp/classes/plugins/PluginRegistry.php(219): PKP\plugins\PluginRegistry::_instantiatePlugin('generic', 'paperbuzz', 'PaperbuzzPlugin')
#1 /home/customer/www/****/public_html/journals/lib/pkp/classes/plugins/PluginRegistry.php(112): PKP\plugins\PluginRegistry::_loadFromDatabase('generic', NULL)
#2 /home/customer/www/****/public_html/journals/lib/pkp/classes/core/Dispatcher.php(155): PKP\plugins\PluginRegistry::loadCategory('generic', true)
#3 /home/customer/www/****/public_html/journals/lib/pkp/classes/core/PKPApplication.php(373): PKP\core\Dispatcher->dispatch(Object(APP\core\Request))
#4 /home/customer/www/****/public_html/journals/index.php(21): PKP\core\PKPApplication->execute()
#5 {main}
[22-Aug-2023 18:27:52 UTC] Exception: Plugin allowedUploads expected to inherit from AllowedUploadsPlugin, actual type NULL in /home/customer/www/****/public_html/journals/lib/pkp/classes/plugins/PluginRegistry.php:203
Stack trace:
#0 /home/customer/www/****/public_html/journals/lib/pkp/classes/plugins/PluginRegistry.php(219): PKP\plugins\PluginRegistry::_instantiatePlugin('generic', 'allowedUploads', 'AllowedUploadsP...')
#1 /home/customer/www/****/public_html/journals/lib/pkp/classes/plugins/PluginRegistry.php(112): PKP\plugins\PluginRegistry::_loadFromDatabase('generic', NULL)
#2 /home/customer/www/****/public_html/journals/lib/pkp/classes/core/Dispatcher.php(155): PKP\plugins\PluginRegistry::loadCategory('generic', true)
#3 /home/customer/www/****/public_html/journals/lib/pkp/classes/core/PKPApplication.php(373): PKP\core\Dispatcher->dispatch(Object(APP\core\Request))
#4 /home/customer/www/****/public_html/journals/index.php(21): PKP\core\PKPApplication->execute()
#5 {main}
[22-Aug-2023 18:27:52 UTC] Exception: Plugin openAIRE expected to inherit from OpenAIREPlugin, actual type NULL in /home/customer/www/****/public_html/journals/lib/pkp/classes/plugins/PluginRegistry.php:203
Stack trace:
#0 /home/customer/www/****/public_html/journals/lib/pkp/classes/plugins/PluginRegistry.php(219): PKP\plugins\PluginRegistry::_instantiatePlugin('generic', 'openAIRE', 'OpenAIREPlugin')
#1 /home/customer/www/****/public_html/journals/lib/pkp/classes/plugins/PluginRegistry.php(112): PKP\plugins\PluginRegistry::_loadFromDatabase('generic', NULL)
#2 /home/customer/www/****/public_html/journals/lib/pkp/classes/core/Dispatcher.php(155): PKP\plugins\PluginRegistry::loadCategory('generic', true)
#3 /home/customer/www/****/public_html/journals/lib/pkp/classes/core/PKPApplication.php(373): PKP\core\Dispatcher->dispatch(Object(APP\core\Request))
#4 /home/customer/www/****/public_html/journals/index.php(21): PKP\core\PKPApplication->execute()
#5 {main}
[22-Aug-2023 18:27:52 UTC] PHP Fatal error:  Uncaught Exception: Invalid product name "ojs-health-sciences" in /home/customer/www/****/public_html/journals/lib/pkp/classes/plugins/PluginRegistry.php:186
Stack trace:
#0 /home/customer/www/****/public_html/journals/lib/pkp/classes/plugins/PluginRegistry.php(219): PKP\plugins\PluginRegistry::_instantiatePlugin('themes', 'ojs-health-scie...', 'HealthSciencesT...')
#1 /home/customer/www/****/public_html/journals/lib/pkp/classes/plugins/PluginRegistry.php(112): PKP\plugins\PluginRegistry::_loadFromDatabase('themes', NULL)
#2 /home/customer/www/****/public_html/journals/lib/pkp/classes/template/PKPTemplateManager.php(1392): PKP\plugins\PluginRegistry::loadCategory('themes', true)
#3 /home/customer/www/****/public_html/journals/lib/pkp/classes/plugins/Plugin.php(403): PKP\template\PKPTemplateManager::getManager(Object(APP\core\Request))
#4 /home/customer/www/****/public_html/journals/lib/pkp/classes/plugins/Plugin.php(137): PKP\plugins\Plugin->_registerTemplateResource()
#5 /home/customer/www/****/public_html/journals/lib/pkp/classes/plugins/LazyLoadPlugin.php(34): PKP\plugins\Plugin->register('generic', 'plugins/generic...', NULL)
#6 /home/customer/www/****/public_html/journals/plugins/generic/pdfJsViewer/PdfJsViewerPlugin.php(31): PKP\plugins\LazyLoadPlugin->register('generic', 'plugins/generic...', NULL)
#7 /home/customer/www/****/public_html/journals/lib/pkp/classes/plugins/PluginRegistry.php(76): APP\plugins\generic\pdfJsViewer\PdfJsViewerPlugin->register('generic', 'plugins/generic...', NULL)
#8 /home/customer/www/****/public_html/journals/lib/pkp/classes/plugins/PluginRegistry.php(121): PKP\plugins\PluginRegistry::register('generic', Object(APP\plugins\generic\pdfJsViewer\PdfJsViewerPlugin), 'plugins/generic...', NULL)
#9 [internal function]: PKP\plugins\PluginRegistry::PKP\plugins\{closure}(Object(APP\plugins\generic\pdfJsViewer\PdfJsViewerPlugin), 'plugins/generic...')
#10 /home/customer/www/****/public_html/journals/lib/pkp/classes/plugins/PluginRegistry.php(121): array_walk_recursive(Array, Object(Closure))
#11 /home/customer/www/****/public_html/journals/lib/pkp/classes/core/Dispatcher.php(155): PKP\plugins\PluginRegistry::loadCategory('generic', true)
#12 /home/customer/www/****/public_html/journals/lib/pkp/classes/core/PKPApplication.php(373): PKP\core\Dispatcher->dispatch(Object(APP\core\Request))
#13 /home/customer/www/****/public_html/journals/index.php(21): PKP\core\PKPApplication->execute()
#14 {main}
  thrown in /home/customer/www/****/public_html/journals/lib/pkp/classes/plugins/PluginRegistry.php on line 186

**Comment by paulyss** [comment]
the theme i installed is the lates one Current version: healthSciences v1.1.2-1 from the readme page. Please help

**Comment by asmecher** [comment]
@paulyss, with apologies for the slow response, did you install the plugin manually? If so, what directory did you install it into?
