### ISSUE TITLE
Archive grid messed up

### ISSUE THREAD

**Issue by geirrosset** [pkp/healthSciences#237]
Installed healtSciences theme for OJS 3.4.0.3 and apart from some missing translations that I fixed easily enough in the po file, the grid view for archived issues is all messed up. In OJS 3.3 the grid was neat with lines of 4 issues. In 3.4 and healthSceinces 1.1.2.1 it looks scrambled with 1, 1, 3, 2, 2, 1, 6, etc.

**Comment by aftechro** [comment]
any chance this will be fixed? just with ojs 3.4 the archive gid shows issues under each others instead of in line

**Comment by aftechro** [comment]
I`m still getting the same, after the new code:
![image](https://github.com/pkp/healthSciences/assets/38830718/afe5933a-7046-472a-8073-f2bba7a875e2)

this should be inline row, atm shows under neath eachothers

**Comment by Vitaliy-1** [comment]
@aftechro, it's issue page with a table of content on the screenshot and the issue that was fixed was related to the issue archive page. Table of content looks ok to me.
