### ISSUE TITLE
Bug in article_summary.tpl for stable-3_3_0

### ISSUE THREAD

**Issue by mirkh** [pkp/healthSciences#241]
**Describe the bug**
Missing dollar sign gives server error 500 when opening journal using this theme in version stable-3_3_0

Line 43:
https://github.com/pkp/healthSciences/blob/stable-3_3_0/templates/frontend/objects/article_summary.tpl

			{submissionPages|escape}
should be

			{$submissionPages|escape}

Error message:

PHP Fatal error:  Uncaught  --> Smarty Compiler: Syntax error in template "app:app:frontendobjectsarticle_summary.tpl"  on line 43 "{submissionPages|escape}" unknown tag 'submissionPages' <-- \n  thrown in app:frontendobjectsarticle_summary.tpl on line 43

Cheers,
Maria

**Comment by asmecher** [comment]
Fixed -- thanks for the detailed report, @mirkh!
