### ISSUE TITLE
Fatal error in editLink.tpl with OJS 3.4.0

### ISSUE THREAD

**Issue by asmecher** [pkp/healthSciences#244]
**Describe the bug**
See https://forum.pkp.sfu.ca/t/ojs-3-4-0-3-fatal-error-uncaught-error-undefined-constant-role-id-manager/88644/4:

when an user, that is not logged in, surfs on a page that is supposed to be publically visible, browser returns a 500 error. I enabled for sake of debugging the “display_errors = On” option
and the complete error output is as follows:

**Fatal error** : Uncaught Error: Undefined constant "ROLE_ID_MANAGER" in /home/account_name/public_html/cache/t_compile/77eab0d48ae26995d2b27ea041d87d954e8d7b1c^e3c52a8a644dae8ad3689fcdc7091f2c0eae2ce2_0.app.frontendcomponentseditLink.tpl.php:24 Stack trace: #0 /home/account_name/public_html/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_66508d9f54e268_74802896(Object(Smarty_Internal_Template)) 
#1 /home/account_name/public_html/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(Smarty_Internal_Template)) 
#2 /home/account_name/public_html/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(217): Smarty_Template_Compiled->render(Object(Smarty_Internal_Template)) 
#3 /home/account_name/public_html/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(386): Smarty_Internal_Template->render() 
#4 /home/account_name/public_html/cache/t_compile/77eab0d48ae26995d2b27ea041d87d954e8d7b1c^63c3703926f6cd217d548df875d7e1620d1ef19f_0.app.frontendpageseditorialTeam.tpl.php(38): Smarty_Internal_Template->_subTemplateRender('app:frontend/co...', NULL, '77eab0d48ae2699...', 0, 3600, Array, 0, false) 
#5 /home/account_name/public_html/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_66508d9f4a1af0_12083082(Object(Smarty_Internal_Template)) 
#6 /home/account_name/public_html/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(Smarty_Internal_Template)) 
#7 /home/account_name/public_html/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(217): Smarty_Template_Compiled->render(Object(Smarty_Internal_Template)) 
#8 /home/account_name/public_html/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(238): Smarty_Internal_Template->render(false, 1) 
#9 /home/account_name/public_html/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(134): Smarty_Internal_TemplateBase->_execute(Object(Smarty_Internal_Template), NULL, '77eab0d48ae2699...', NULL, 1) 
#10 /home/account_name/public_html/lib/pkp/classes/template/PKPTemplateManager.php(1325): Smarty_Internal_TemplateBase->display('frontend/pages/...', NULL, '77eab0d48ae2699...', NULL) 
#11 /home/account_name/public_html/lib/pkp/pages/about/AboutContextHandler.php(66): PKP\template\PKPTemplateManager->display('frontend/pages/...') 
#12 [internal function]: PKP\pages\about\AboutContextHandler->editorialTeam(Array, Object(APP\core\Request)) 
#13 /home/account_name/public_html/lib/pkp/classes/core/PKPRouter.php(334): call_user_func(Array, Array, Object(APP\core\Request)) 
#14 /home/account_name/public_html/lib/pkp/classes/core/PKPPageRouter.php(277): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(APP\core\Request), Array, false) 
#15 /home/account_name/public_html/lib/pkp/classes/core/Dispatcher.php(165): PKP\core\PKPPageRouter->route(Object(APP\core\Request)) 
#16 /home/account_name/public_html/lib/pkp/classes/core/PKPApplication.php(387): PKP\core\Dispatcher->dispatch(Object(APP\core\Request)) 
#17 /home/account_name/public_html/index.php(21): PKP\core\PKPApplication->execute() 
#18 {main} thrown in **/home/account_name/public_html/cache/t_compile/77eab0d48ae26995d2b27ea041d87d954e8d7b1c^e3c52a8a644dae8ad3689fcdc7091f2c0eae2ce2_0.app.frontendcomponentseditLink.tpl.php** on line **24**

**Comment by ajnyga** [comment]
@asmecher this is in Pragma as well

**Comment by asmecher** [comment]
@ajnyga Thanks, I've ported this to `stable-3_4_0` and `main` for Pragma.

**Comment by nwoodward** [comment]
We observed this error in the Immersion theme as well. Applying the same namespace fix to https://github.com/pkp/immersion/blob/9348da7dcf0678583047c15c88a49c27012f9ee9/templates/frontend/components/editLink.tpl#L18 fixed it.
