### ISSUE TITLE
Missing ids for checkboxes on user registration form

### ISSUE THREAD

**Issue by kaitlinnewson** [pkp/healthSciences#249]
**Describe the bug**
The two consent check boxes on the user registration form are missing `id` attributes, which should be the same as the existing `name` attributes and the associated label. This means the labels are not properly associated with the inputs, and is an accessibility issue.

This issue is present in the 3.3, 3.4, and main branches.

**Additional context**

https://github.com/pkp/healthSciences/blob/e5255ba24bbdbee437f0bc64ba5be1b599ec140f/templates/frontend/components/registrationForm.tpl#L122

https://github.com/pkp/healthSciences/blob/e5255ba24bbdbee437f0bc64ba5be1b599ec140f/templates/frontend/components/registrationForm.tpl#L133

**Comment by kaitlinnewson** [comment]
PR for review:

- main: https://github.com/pkp/healthSciences/pull/250

Will also need to be backported for 3.3/3.4.

**Comment by asmecher** [comment]
Both PRs merged, thanks!
