### ISSUE TITLE
deprecation warnings in footer template

### ISSUE THREAD

**Issue by OyvindLGjesdal** [pkp/healthSciences#258]
**Describe the bug**

After upgrading to php 8.2, I see deprecation warning and smarty warning:

``` Using php-function "trim" as a modifier is deprecated and will be removed in a future release. Use Smarty::registerPlugin to explicitly register a custom modifier. in /var/www/ojs/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_compile_private_modifier.php on line 112
PHP Deprecated:  trim(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/ojs/cache/t_compile/..._0.app.frontendcomponentsfooter.tpl.php on line 57
```

refers to 

https://github.com/pkp/healthSciences/blob/main/templates/frontend/components/footer.tpl#L36

```
{* Load author biography modals if they exist *}
{if !empty($smarty.capture.authorBiographyModals|trim)}
	{$smarty.capture.authorBiographyModals}
{/if}
```

Would skipping the trim filter make sense (if it exists as whitespace, it will only input whitespace).

I don't know if this is fixed upstream in smarty, but the smarty version used is the same as the in 3.3 stable branch of pkp-lib, which is 0.2 versions behind main. (v4.3.1).

**Comment by asmecher** [comment]
@OyvindLGjesdal, what version of OJS are you using, and what version of the health sciences theme?

**Comment by OyvindLGjesdal** [comment]
3.3.0.17 and a bit behind on the the healthSciences theme 722d2ba

I did a fast check in the stable-3.3 branch for both ojs and the theme to see if the section had changed, or the library version, and it looked likely to me, that the bug was also present there. Haven't confirmed.

**Comment by asmecher** [comment]
@OyvindLGjesdal, can you quickly verify if this change resolves the issue?
```diff
diff --git a/templates/frontend/components/footer.tpl b/templates/frontend/components/footer.tpl
index 3b3e6f2..126ea2c 100644
--- a/templates/frontend/components/footer.tpl
+++ b/templates/frontend/components/footer.tpl
@@ -33,7 +33,7 @@
 </footer><!-- pkp_structure_footer_wrapper -->
 
 {* Load author biography modals if they exist *}
-{if !empty($smarty.capture.authorBiographyModals|trim)}
+{if !empty($smarty.capture.authorBiographyModals|default:""|trim)}
        {$smarty.capture.authorBiographyModals}
 {/if}
```

**Comment by OyvindLGjesdal** [comment]
I get a different deprecation message:

```
PHP Deprecated:  Using php-function "trim" as a modifier is deprecated and will be removed in a future release. Use Smarty::registerPlugin to explicitly register a custom modifier. in /var/www/ojs/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_compile_private_modifier.php on line 112
```

**Comment by asmecher** [comment]
@OyvindLGjesdal You're right, thanks -- added here for `stable-3_3_0`:

https://github.com/pkp/pkp-lib/blob/90a2a55f71d1eac01ef7ba86d8c854d00ad236e6/classes/template/PKPTemplateManager.inc.php#L260

For 3.4.0, it's https://github.com/pkp/pkp-lib/commit/c91897c76bf94cc02ae7e1122fdc6824b6edfeed; for `main` it's https://github.com/pkp/pkp-lib/commit/cb47652b63e5cecb92deedf21fdfc3e5cb1750e5.
