### ISSUE TITLE
Article title

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/healthSciences#29]
The subtitle should be separated from the title with a colon without any differences in font size or color.

**Comment by NateWr** [comment]
The `PKPString::concatTitleFields` method is what you're looking for. :+1:

**Comment by NateWr** [comment]
There's also `Submission::getLocalizedFullTitle()` which calls that if a subtitle exists.

**Comment by Vitaliy-1** [comment]
Hah! It's impressive how you've anticipated this, thanks :)
