### ISSUE TITLE
Styles issues on installation using zip files

### ISSUE THREAD

**Issue by kwahyu** [pkp/healthSciences#46]
Dear @Vitaliy-1 
We installed the theme in this http://ulumuna.or.id/index.php/ujis/index by downloading the zip files in Codes
However, some issues fixed in Closed Issues are not there, e.g. dropdown menu, the size of article title, no search menu etc.
e.g. http://ulumuna.or.id/index.php/ujis/about   http://ulumuna.or.id/index.php/ujis/article/view/274

We compared to https://demo.publicknowledgeproject.org/ojs3/demo/index.php/health-sciences
Is it the correct method to install using the zip file? or should have installed codes from the release?
We have tried clear template cache but nothing changes
Thanks

**Comment by Vitaliy-1** [comment]
When you have downloaded it?

**Comment by Vitaliy-1** [comment]
Checked the release source file once more -> all looks OK.
My steps for trying to reproduce:
1. Download the latest release: https://github.com/pkp/healthSciences/releases/tag/1.0.0
2. Setting right permissions to the plugins directory.
3 Upload the archive through the admin dashboard (settings->website->plugins->upload new plugin
4. Waiting the green notice that plugin successfully installed.
5. Enambling the plugin and switching in the appearence menu.
6. Clearing template cache.

Result: http://dev-ojs.e-medjournal.com/index.php/sjt

@kwahyu Did you perform all this steps?

**Comment by kwahyu** [comment]
In Codes - Clone or download - Download Zip. We did it today and installing through cpanel. Which style is that? We just moved up the additional content. We did not follow your 6 steps installation.

**Comment by kwahyu** [comment]
Thanks a lot @Vitaliy-1 
It is normal now
