### ISSUE TITLE
Issues on acrhive are not sequential

### ISSUE THREAD

**Issue by kwahyu** [pkp/healthSciences#48]
Dear @Vitaliy-1 
The issues on archive http://ulumuna.or.id/index.php/ujis/issue/archive are not sequential. We have checked in back issue, each is in correct order.

**Comment by Vitaliy-1** [comment]
Is the order normal in other themes?

**Comment by kwahyu** [comment]
I tried switching to default manuscript, it is not normal either.

**Comment by Vitaliy-1** [comment]
I rememeber that users reported about problems with issue ordering on the archive page but not any specific cause. Maybe with quick submit plugin. Maybe @NateWr knows better.

**Comment by NateWr** [comment]
https://github.com/pkp/pkp-lib/issues/3705
