### ISSUE TITLE
Change header gray color to another one?

### ISSUE THREAD

**Issue by EduardoOsquel** [pkp/healthSciences#71]
I really need to change the header background color for this theme. I need help!!!

**Comment by Vitaliy-1** [comment]
For the header? Hmm, that will require some knowledge of CSS. Are you still working on this?

**Comment by EduardoOsquel** [comment]
@Vitaliy-1 Thanks my friend, i find this solution... custom CSS obviously!

**Comment by sssoz** [comment]
@EduardoOsquel Thanks for writing! I helped design this theme, and I’m interested in seeing what real users are doing with it for later improvements (as well as suggesting different customisation features in new themes). Would you mind sharing your journal’ URL here?
