### ISSUE TITLE
Not possible to upload the plugin through admin dashboard

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/healthSciences#9]
Greetings,

This is the first thing that I have encountered.  Had the same while uploading own plugins archived in tar.gz format. 
Notification: The uploaded plugin archive does not contain a folder that corresponds to the plugin name.
Console log: 
```
pkp.min.js:231 Uncaught TypeError: this.unbindPartial is not a function
    at c (pkp.min.js:231)
    at pkp.min.js:231
```
Nothing in the error log.

**Comment by NateWr** [comment]
@Vitaliy-1 this sounds like https://github.com/pkp/healthSciences/issues/2. Are you sure you used the [beta](https://github.com/pkp/healthSciences/releases/tag/beta1) release as it should be fixed. there.

**Comment by Vitaliy-1** [comment]
Quite sure. Latest stable OJS release and the beta release of the theme plugin.

**Comment by NateWr** [comment]
I'm having trouble replicating this one as well. Is it possible that you used one of the source code packages that GitHub builds automatically? The **healthSciences-beta.tar.gz** is the one to try.

![selection_101](https://user-images.githubusercontent.com/2306629/38022265-f35a7ce8-3276-11e8-832b-2d63888c93e7.png)

**Comment by Vitaliy-1** [comment]
Nope, I have tried this archive.

**Comment by NateWr** [comment]
Hmm, I don't know what to say but if it's a common problem we'll find out fast once it's released. :) Sorry I couldn't replicate it.

**Comment by Vitaliy-1** [comment]
Hi again. I confirm that on my test installation on Ubuntu server I can download the plugin through the dashboard.  Suppose that is the Windows 10 issue.
